services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml 
